name: "菠萝包轻小说注册"
run-name: "OP要喝OP果奶"
on:
  schedule:
    - cron: "55 1,9 * * *" # 北京时间上午 9:55 AM，下午 5:55 PM 运行，注册一个号
  workflow_dispatch: # 允许手动触发工作流
jobs:
  run-ts-script:
    runs-on: windows-latest
    environment: supabase
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install
        run: npm ci

      - name: ts-node run
        env:
          SMS_USERNAME: ${{ secrets.SMS_USERNAME }}
          SMS_PASSWORD: ${{ secrets.SMS_PASSWORD }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          REGIST_PASSWORD: ${{ secrets.REGIST_PASSWORD }}
        run: npm run register

      # # 其他可能的优化步骤
      # - name: Cache node modules
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-
